define USAGE
Charts with flask ⚙️

Commands:
	init      Install Python dependencies
	run       Run app in dev environment.
endef

export USAGE
help:
	@echo "$$USAGE"

init:
	pip install -r requirements.txt

run:
	python app.py
